After refactoring
magnifiq/task2_internship pull request #4
Opened 2023-09-22 11:27 UTC by magnifiq

2023-09-24 14:28 UTC, igorTT requested changes
Don't create a separate branch to fix problems from another branch. Return back to the branch where you got the review and fix the problem there instead of creating a new one.

2023-09-24 14:28 UTC, igorTT commented on form.js
> +function appSubEl(parent, child){
Don't reduce append to 'app'.
Get the second parameter as ...rest.
Append children's elements through the cycle.

2023-09-24 14:28 UTC, igorTT commented on form.js
> +function createNewAttr(el, atr, val){
It doesn't create something new. It adds an attribute. Get the object as a second parameter.
atr -> attr

2023-09-24 14:28 UTC, igorTT commented on form.js
> +}
Let's use function declaration in the places where we need to work with context. Use arrow functions instead to be more consistent.

2023-09-25 19:55 UTC, igorTT requested changes
Configure IDE to fix such problems automaticaly

2023-09-25 19:55 UTC, igorTT commented on form.js
> +const createNewEl=(el)=>{
should be empty space betwwen function name, etc...
```javascript
const createNewEl = (el) => {
...
```

2023-09-25 19:55 UTC, igorTT commented on form.js
> +}
Missing semicolon

2023-09-28 07:13 UTC, igorTT requested changes
I don't see any changes since the last code review.

2023-09-28 16:59 UTC, magnifiq commented
I committed changes to bugfix/3 branch

2023-09-28 20:13 UTC, igorTT commented
> I committed changes to bugfix/3 branch

But I added a comment to the current pull request, not to the bugfix/3

2023-10-01 16:30 UTC, igorTT approved these changes

2023-10-01 16:39 UTC, merged