Bugfix/3
magnifiq/task2_internship pull request #5
Opened 2023-09-22 11:40 UTC by magnifiq

After the addition of an event listener

2023-09-24 14:24 UTC, igorTT requested changes
please check target branch to reduce changes.

2023-09-24 14:24 UTC, igorTT commented on form.js
> +}
function returns not the element, but its value. Rename to getElementValue.

2023-09-24 14:24 UTC, igorTT commented on form.js
> +  console.log(getEl("password"));
You already have access to these two elements -> inputEmail and inputPassword

2023-09-28 07:10 UTC, igorTT requested changes
The pull request should contain only the functionality described in the issue (add event listeners)

2023-09-28 17:52 UTC, magnifiq commented
ok, I understood, but I added the local storage and a loading state here. Do I need to add this changes to the solved_first branch?

2023-09-28 20:16 UTC, igorTT commented
> ok, I understood, but I added the local storage and a loading state here. Do I need to add this changes to the solved_first branch?

This pull request should contain only changes related to the current issue (add event listeners). All other issues should be solved in separate branches.

2023-10-01 16:43 UTC, igorTT approved these changes

2023-10-01 16:43 UTC, merged